[phases.setup]
nixpkgs = [
  "gcc",
  "libstdc++6",
  "sqlite",
  "pkg-config",
  "python3"
]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run src/index.ts"

