[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./railway-start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
numReplicas = 1

# Resource limits to prevent OOM kills
[deploy.resources]
memory = "512Mi"
cpu = "0.5"

# Environment-specific settings
[environments.production]
variables = { 
  NODE_ENV = "production",
  # Ensure Railway uses the correct port
  PORT = "${{ PORT }}",
  # Prevent timeouts during startup
  RAILWAY_HEALTHCHECK_TIMEOUT = "300"
} 