[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./railway-start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
numReplicas = 1

# Resource limits to prevent OOM kills and ensure stability
[deploy.resources]
memory = "1Gi"
cpu = "1"

# Environment-specific settings
[environments.production]
variables = { 
  NODE_ENV = "production",
  PORT = "${{ PORT }}",
  RAILWAY_HEALTHCHECK_TIMEOUT = "300",
  SQLITE_TMPDIR = "/tmp",
  # Increase Node.js memory limit
  NODE_OPTIONS = "--max-old-space-size=768"
} 